version: '3'

services:
  socket:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: web-socket
    image: pk-akr-socket
    ports:
      - "${SOCKET_PORT}:${SOCKET_PORT}"
    env_file:
      .env
    command: bash -c "python main,py"
